### ISSUE TITLE
tried on both Windows and Ubuntu - not working...

### ISSUE THREAD

**Issue by tschrist** [SkullTech/goodreads-giveaways#4]
after entering name and password, always returns the following

Traceback (most recent call last):
  File "giveaways.py", line 102, in <module>
    main()
  File "giveaways.py", line 88, in main
    login(session, username, password)
  File "giveaways.py", line 11, in login
    form = tree.xpath('//div[@id="signInForm"]')[0]
IndexError: list index out of range

I've even checked by resetting my password - I use my email and password to login online, but always this error with the script

**Comment by vaibhavpacharya** [comment]
+1

**Comment by vaibhavpacharya** [comment]
@skulltech any update on this?

**Comment by skulltech** [comment]
Hey @vaibhavpacharya sorry I totally missed this. Will look into this.

**Comment by dlnl3** [comment]
any chance you'll work on this again?
